language: java

jdk:
  - oraclejdk8

script:
  - gradle check
  - gradle test jacoco

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ -z "$TRAVIS_TAG" ]; then gradle bintrayUpload; fi