language: java

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew test jacoco

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ -z "$TRAVIS_TAG" ]; then ./gradlew bintrayUpload; fi